// do the correct imports to use page.factory and credentials enum
// you may need to create new Page Object Model Classes and Steps !
// do this in the normal project area playwright/pages and playwright/steps
// but keep your scenario spec file in your homework folder
// after all homeworks are done I will replace the Page and Step files with the example solutions ones

// scenario 1:
// where we check the business plan details offered by the test site
// login to the test site 'https://st2016.inv.bg/login/', use credentials enum for login details
// navigate to "Нова Фактура" page, verify you are on the correct page
// click on the box link "Преминете на по-висок план", navigating to a new page, verify you are on the correct page
// test each payment plan (make the scenario parametrized data driven scenario with 5 sets): corporate plan, business plan, small business plan, personal plan and free plan
// verify each plan's details: cost (Lev and Euro), benefits (client number, invoices, employees number), other benefits (logo, signature etc.)

// scenario 2:
// where we verify client creation and deletion
// login to the test site 'https://st2016.inv.bg/login/', use credentials enum for login details
// navigate to page "Клиенти"`, verify you are on the correct page
// click button "Нов Клиент", verify you are on the correct page
// fill in "New Client" from's Name with random name generated by faker and click the "Запази" button, Verify success message (you may need to execute `npm install` to install the faker library as its new to the project)
// click on "Списък с Клиенти", verify navigation
// check the checkbox next to the newly created client (using dynamic arrow method locator), click the delete button, accept the message box (not a pop up this time), verify success message

import { test } from '@tests/steps/step.factory';
import { Credentials } from '@tests/resourses/enums/Credentials';
import { expect } from '@playwright/test';

type BusinessPlan = {
  index: number;
  name: string;

  costs: string[];

  clientCount: number;
  invoicesCount: number;
  employeesCount: number;

  otherBenefits: string[];
};

const businessPlans: BusinessPlan[] = [
  {
    index: 0,
    name: 'Корпоративен',
    costs: ['по договаряне'],
    clientCount: 10,
    invoicesCount: 100,
    employeesCount: 5,
    otherBenefits: ['Logo', 'Signature'],
  },
  {
    index: 1,
    name: 'Бизнес',
    costs: ['28 €/месец', '54.76 лв./месец'],
    clientCount: 5,
    invoicesCount: 50,
    employeesCount: 5,
    otherBenefits: ['Logo', 'Signature'],
  },
  {
    index: 2,
    name: 'Малък бизнес',
    costs: ['8 €/месец', '15.65 лв./месец'],
    clientCount: 5,
    invoicesCount: 50,
    employeesCount: 5,
    otherBenefits: ['Logo', 'Signature'],
  },
];

// test data parametrization for multiple scenarios:
[
  // scenario 1:
  {
    scenario: 'Scenario 1: Corporate plan Details Verification',
    email: Credentials.EMIAL,
    password: Credentials.PASSWORD,
    usingEnterKey: false,
  },
  // pass the test data params forward to the test function:
].forEach(({ email, password, usingEnterKey, scenario }) => {
  test(
    `Scenario: ${scenario}`, // test scenario title + param 'scenario' to make the title unique for each scenario
    {
      tag: ['@ui', '@login', '@positive'], // tags for scenario categorization
      annotation: [
        // annotations for better reporting:
        { type: 'Test Managmetn Id', description: '12312312' },
        { type: 'username', description: email },
        { type: 'password', description: password },
      ],
    }, // inject fixtures here to be able to use their steps in the test body:
    async ({ sharedSteps, landintSteps, newInvoiceSteps }) => {
      // finally actual test body containing calls to test step definitions executing our code:
      await sharedSteps.navigateToSite('https://st2016.inv.bg/login/');
      await sharedSteps.login(email, password, usingEnterKey);

      await landintSteps.navigateToNewInvoicePage();

      await newInvoiceSteps.navigateToNewPlanPage();

      businessPlans.forEach(async (businessPlan) => {
        await newInvoiceSteps.verifyBusinessPlanName(businessPlan.name);

        businessPlan.costs.forEach(async (cost) => {
          await newInvoiceSteps.verifyBusinessPlanCosts(cost);
        });
      });
    },
  );
});
