// do the correct imports to use page.factory and credentials enum
// you may need to create new Page Object Model Classes and Steps !
// do this in the normal project area playwright/pages and playwright/steps
// but keep your scenario spec file in your homework folder
// after all homeworks are done I will replace the Page and Step files with the example solutions ones

// scenario 1:
// where we check the business plan details offered by the test site
// login to the test site 'https://st2016.inv.bg/login/', use credentials enum for login details
// navigate to "Нова Фактура" page, verify you are on the correct page
// click on the box link "Преминете на по-висок план", navigating to a new page, verify you are on the correct page
// test each payment plan (make the scenario parametrized data driven scenario with 5 sets): corporate plan, business plan, small business plan, personal plan and free plan
// verify each plan's details: cost (Lev and Euro), benefits (client number, invoices, employees number), other benefits (logo, signature etc.)

// scenario 2:
// where we verify client creation and deletion
// login to the test site 'https://st2016.inv.bg/login/', use credentials enum for login details
// navigate to page "Клиенти"`, verify you are on the correct page
// click button "Нов Клиент", verify you are on the correct page
// fill in "New Client" from's Name with random name generated by faker and click the "Запази" button, Verify success message (you may need to execute `npm install` to install the faker library as its new to the project)
// click on "Списък с Клиенти", verify navigation
// check the checkbox next to the newly created client (using dynamic arrow method locator), click the delete button, accept the message box (not a pop up this time), verify success message

//Scenario 1: Payment Plan Details Verification

import { test } from '@tests/steps/step.factory';
import { Credentials } from '@tests/resourses/enums/Credentials';

[
  {
    scenario: 'Scenario 1: Case 1: Corporate Payment Plan Details Verification',
    email: Credentials.EMIAL,
    password: Credentials.PASSWORD,
    usingEnterKey: false,
    name: 'Корпоративен',
    costs: ['по договаряне'],
    clientCount: 'неограничени',
    invoicesCount: 'неограничени',
    employeesCount: 'неограничени',
    otherBenefits: ['REST API за достъп', 'допълнително архивиране', 'приоритетен support'],
  },
  {
    scenario: 'Scenario 1: Case 2: Business Payment Plan Details Verification',
    email: Credentials.EMIAL,
    password: Credentials.PASSWORD,
    usingEnterKey: false,
    name: 'Бизнес',
    costs: ['28 €/месец', '54.76 лв./месец'],
    clientCount: '1000 клиента',
    invoicesCount: '1000 фактури/месец',
    employeesCount: '25 служителя',
    otherBenefits: ['с Ваше лого', 'с електронен подпис'],
  },
  {
    scenario: 'Scenario 1: Case 3: Small Business Payment Plan Details Verification',
    email: Credentials.EMIAL,
    password: Credentials.PASSWORD,
    usingEnterKey: false,
    name: 'Малък бизнес',
    costs: ['8 €/месец', '15.65 лв./месец'],
    clientCount: '150 клиента',
    invoicesCount: '150 фактури/месец',
    employeesCount: '10 служителя',
    otherBenefits: ['с Ваше лого', 'с електронен подпис'],
  },
  {
    scenario: 'Scenario 1: Case 4: Personal Payment Plan Details Verification',
    email: Credentials.EMIAL,
    password: Credentials.PASSWORD,
    usingEnterKey: false,
    name: 'Персонален',
    costs: ['4 €/месец', '7.82 лв./месец'],
    clientCount: '15 клиента',
    invoicesCount: '15 фактури/месец',
    employeesCount: '1 служителя',
    otherBenefits: ['с Ваше лого'],
  },
  {
    scenario: 'Scenario 1: Case 5: Free Payment Plan Details Verification',
    email: Credentials.EMIAL,
    password: Credentials.PASSWORD,
    usingEnterKey: false,
    name: 'Безплатен',
    costs: ['0 €/месец', '0 лв./месец'],
    clientCount: '5 клиента',
    invoicesCount: '5 фактури/месец',
    employeesCount: '1 служителя',
    otherBenefits: [],
  },
].forEach(
  ({
    email,
    password,
    usingEnterKey,
    scenario,
    name,
    costs,
    clientCount,
    invoicesCount,
    employeesCount,
    otherBenefits,
  }) => {
    test(
      `${scenario}`,
      {
        tag: ['@ui', '@login', '@positive'],
        annotation: [
          { type: 'username', description: email },
          { type: 'password', description: password },
        ],
      },
      async ({ sharedSteps, landintSteps, newInvoiceSteps }) => {
        await sharedSteps.navigateToSite('https://st2016.inv.bg/login/');
        await sharedSteps.login(email, password, usingEnterKey);

        await landintSteps.navigateToNewInvoicePage();

        await newInvoiceSteps.navigateToNewPlanPage();

        await newInvoiceSteps.verifyPlanName(name);

        costs.forEach(async (cost) => {
          await newInvoiceSteps.verifyPlanCosts(cost);
        });

        await newInvoiceSteps.verifyBenefits(name, employeesCount, invoicesCount, clientCount);

        await otherBenefits.forEach(async (benefit) => {
          await newInvoiceSteps.verifyOtherBenefits(name, benefit);
        });
      },
    );
  },
);
