// do the correct imports to use page.factory and credentials enum
// you may need to create new Page Object Model Classes and Steps !
// do this in the normal project area playwright/pages and playwright/steps
// but keep your scenario spec file in your homework folder
// after all homeworks are done I will replace the Page and Step files with the example solutions ones

// scenario 1:
// where we check the business plan details offered by the test site
// login to the test site 'https://st2016.inv.bg/login/', use credentials enum for login details
// navigate to "Нова Фактура" page, verify you are on the correct page
// click on the box link "Преминете на по-висок план", navigating to a new page, verify you are on the correct page
// test each payment plan (make the scenario parametrized data driven scenario with 5 sets): corporate plan, business plan, small business plan, personal plan and free plan
// verify each plan's details: cost (Lev and Euro), benefits (client number, invoices, employees number), other benefits (logo, signature etc.)

// scenario 2:
// where we verify client creation and deletion
// login to the test site 'https://st2016.inv.bg/login/', use credentials enum for login details
// navigate to page "Клиенти"`, verify you are on the correct page
// click button "Нов Клиент", verify you are on the correct page
// fill in "New Client" from's Name with random name generated by faker and click the "Запази" button, Verify success message (you may need to execute `npm install` to install the faker library as its new to the project)
// click on "Списък с Клиенти", verify navigation
// check the checkbox next to the newly created client (using dynamic arrow method locator), click the delete button, accept the message box (not a pop up this time), verify success message

import { test } from '@tests/steps/step.factory';
import { Credentials } from '@tests/resourses/enums/Credentials';

[
  {
    scenario: 'Корпоративен',
    username: Credentials.EMIAL,
    password: Credentials.PASSWORD,
    expected: {
      planName: 'Корпоративен',
      euroPrice: null,
      levPrice: null,
      clients: 'неограничени',
      invoices: 'неограничени',
      employees: 'неограничени',
      features: ['REST API', 'допълнително архивиране', 'приоритетен support'],
    },
  },
  {
    scenario: 'Бизнес',
    username: Credentials.EMIAL,
    password: Credentials.PASSWORD,
    expected: {
      planName: 'Бизнес',
      euroPrice: '28 €/месец',
      levPrice: '54.76 лв./месец',
      clients: '1000',
      invoices: '1000',
      employees: '25',
      features: ['с Ваше лого', 'с електронен подпис'],
    },
  },
  {
    scenario: 'Малък Бизнес',
    username: Credentials.EMIAL,
    password: Credentials.PASSWORD,
    expected: {
      planName: 'Малък Бизнес',
      euroPrice: '8 €/месец',
      levPrice: '15.65 лв./месец',
      clients: '150',
      invoices: '150',
      employees: '10',
      features: ['с Ваше лого', 'с електронен подпис'],
    },
  },
  {
    scenario: 'Персонален',
    username: Credentials.EMIAL,
    password: Credentials.PASSWORD,
    expected: {
      planName: 'Персонален',
      euroPrice: '4 €/месец',
      levPrice: '7.82 лв./месец',
      clients: '15',
      invoices: '15',
      employees: '1',
      features: ['с Ваше лого'],
    },
  },
  {
    scenario: 'Безплатен',
    username: Credentials.EMIAL,
    password: Credentials.PASSWORD,
    expected: {
      planName: 'Безплатен',
      euroPrice: '0 €/месец',
      levPrice: '0 лв./месец',
      clients: '5',
      invoices: '5',
      employees: '1',
      features: [],
    },
  },
].forEach(({ scenario, username, password, expected }) => {
  test(
    `Verify Business Plan: ${scenario}`,
    {
      tag: ['@ui', '@businessplan'],
      annotation: [
        { type: 'username', description: username },
        { type: 'password', description: password },
      ],
    },
    async ({ sharedSteps, landingSteps, newInvoiceSteps, planSteps }) => {
      await sharedSteps.navigateToSite('https://st2016.inv.bg/login/');
      await sharedSteps.login(username, password);
      await landingSteps.navigateToNewInvoicePage();
      await newInvoiceSteps.upgradePlan();
      await planSteps.verifyPlan(scenario, expected);
    },
  );
});
